### ISSUE TITLE
git via ssh - (maybe) require a shell

### ISSUE THREAD

**Issue by DO1JLR** [thomas-maurice/ansible-role-gitea#14]
By performing git via ssh I got this error:
```bash
$ git pull
fatal: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
```
If I just try to ssh directly to the gitea server as user gitea, I got the error 
```bash
PTY allocation request failed on channel 0
Connection to gitea.localhost closed.
```
I fixed the error by giving the user ``gitea`` a shell (``/bin/bash``) instead of ``/bin/false``.

And now git over ssh works like usual.

And if I know ssh directly to the host, it looks usual to me:
```bash
$ ssh gitea@gitea.localhost
PTY allocation request failed on channel 0
Hi there, You've successfully authenticated, but Gitea does not provide shell access.
If this is unexpected, please log in with password and setup Gitea under another user.
Connection to gitea.localhost closed.
```
I changed it here: https://github.com/DO1JLR/ansible-role-gitea/commit/c8602dd5504a6ca47475b6dfe43c9ca9cd05194c
Should I create a pull request or is this probably a issue with the ssh roles I use *([add users + keys](https://github.com/ffbsee/role-ssh_authorized_keys) and [configure sshd](https://github.com/DO1JLR/role_sshd))*

**Comment by thomas-maurice** [comment]
Interesting, I will try to repro on a vanilla instance over the weekend, thanks for reporting it

**Comment by thomas-maurice** [comment]
So I tried to repro, I spinned a vanilla GCP instance and ran the playbook, I was able to pull/push to the repos created over SSH like I do on my "production" personal instance without any issue.

```
root tmp ~ # cat /etc/debian_version 
9.7
root tmp ~ # grep gitea /etc/passwd
gitea:x:1001:1002:Gitea user:/var/lib/gitea:/bin/false
root tmp ~ # 
```

The gitea process is running as the user it should:
```
gitea    29171  0.1 16.5 622528 100576 ?       Ssl  11:42   0:01 /usr/local/bin/gitea web -c /etc/gitea/gitea.ini
```

Which distro are you using ?

**Comment by thomas-maurice** [comment]
Also if the mitigation is as simple as giving a shell to the gitea user, you can do a PR if you want to *optionally* give a shell to the user that's not `/bin/false` but I'd rather have it disabled by default for security reasons.

**Comment by DO1JLR** [comment]
Hi, sorry for the delay. I was a little busy...

The user for gitea is gitea:
```bash
 $ ps auxw  | grep gitea
debian     342  0.0  0.0  12716   940 pts/0    S+   10:53   0:00 grep --color=auto gitea
gitea    18434  0.0  2.1 829288 88832 ?        Ssl  Mar28   7:26 /usr/local/bin/gitea web -c /etc/gitea/gitea.ini

```

I am running debian too:
```bash
 $ cat /etc/debian_version 
9.8
 $ grep gitea /etc/passwd
gitea:x:1003:1004:Gitea user:/var/lib/gitea:/bin/bash
```

and the issue is still present.

I will make a pull request soon™ with the option to change ``/bin/false`` to something else.

**Comment by reikjarloekl** [comment]
Same issue here with debian_version 10.2, Putty tells me that 
`Server refused to allocate pty` when shell is set to /bin/false

**Comment by DO1JLR** [comment]
> Same issue here with debian_version 10.2, Putty tells me that
> `Server refused to allocate pty` when shell is set to /bin/false

My work around is this option in my ansible vars:
```ini
gitea_shell: "/bin/bash
```

**Comment by zeus86** [comment]
from the gitea docs onto this topic:
(https://docs.gitea.io/en-us/faq/#ssh-issues)
`Make sure that the git system user has a usable shell set `
...this is true at least for the systems' ssh-server
