### ISSUE TITLE
Fix the quality score for the package

### ISSUE THREAD

**Issue by thomas-maurice** [thomas-maurice/ansible-role-gitea#17]
I suspect the version check PR introduced things the linter didnt like very much
* E601:  Don't compare to literal True/False
* E306:  Shells that use pipes should set the pipefail option

That should be fixed at some point.

**Comment by thomas-maurice** [comment]
FYI @trysdyn I'll add you to the review

**Comment by thomas-maurice** [comment]
https://github.com/thomas-maurice/ansible-role-gitea/pull/18 here since i cannot add you as a reviewer

**Comment by trysdyn** [comment]
Gah! Sorry about that.

Looks fine to me; at least it was a simple change. I'm going to blame old Puppet habits :(

**Comment by thomas-maurice** [comment]
No worries at all :p thanks for the review !

Score is now back to 5/5 on trip advisor, closing this one :D
