### ISSUE TITLE
Couldnt start gitea service?

### ISSUE THREAD

**Issue by thepenguinthatwants** [thomas-maurice/ansible-role-gitea#35]
Hi!

I am trying to install gitea on ubuntu 18.04.

 After trying to start the service I get

 gitea.service: Failed to reset devices.list: Operation not permitted

Any clue how to solve it?

**Comment by DO1JLR** [comment]
@thepenguinthatwants found the issue or still need help?

**Comment by thepenguinthatwants** [comment]
Hi!

I am running this on LXC so I guess this problem is not related to this role as it installs fine and 
`curl localhost:9000 `
works.


but using browser to go the site like 10.62.216.20:9000 I get nothing cant manage to login page only browser Unable to connect.. so I guess there is something else going on.

**Comment by JensTimmerman** [comment]
@thepenguinthatwants have you configured `    gitea_http_listen: 0.0.0.0` or is it set as the default `    gitea_http_listen: 127.0.0.1` ?
