### ISSUE TITLE
Template not idempotent

### ISSUE THREAD

**Issue by zeus86** [thomas-maurice/ansible-role-gitea#70]
Although I modified the the playbook for my needs, I think this will still apply also on an unmodified playbook. 

Somehow the task "Configure gitea" is not idempotent (not sure why, because it basically just copies a file generated from the config template). Because of this, the deamon-restart gets notified every time, and the service is also restarted every time. 

I use ansible 2.9.6 on ubuntu 20.04 from the ubuntu repos (both, server and client are ubuntu 20.04)

**Comment by zeus86** [comment]
Already found it. 
The problem is in the creation of the home-dir and the config path. You should add also a "group" for the files, not just a user (preferrably named both the same, e.g. "gitlab"). Without a group, all files belong to '{{ gitea_user }}:root' , but every file inside the homedir created by gitea during operation belongs to  '{{ gitea_user }}:$primaryGroupOfGitea_User'. 
On the next run, the directory-creation-job has changed, because the group is different than default, which would be 'root'. 
The result is that the config changes (it's group) -> systemd get notified -> the service restarts. 

...just add "group:" to the task...

**Comment by DO1JLR** [comment]
In my gitea installation I have enabled lfs (`gitea_lfs_server_enabled: true`).
Thereby the variable `LFS_JWT_SECRET` is generated by gitea with a unique string. See also [config cheat sheet](https://docs.gitea.io/en-us/config-cheat-sheet/). 

This would still have to be included in the template to become idempotent again.

**Comment by DO1JLR** [comment]
any chance you could have a look at the linked pull requests @thomas-maurice ?
