### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by wzzrd** [thomas-maurice/ansible-role-gitea#82]
Hi Thomas,

thanks for this role, it is awesome and really helpful in maintaining my Gitea server.

One small request I have is to implement versioning and tagging for this role. It would be good if it would be possible to deploy a known working or older version for some scenarios.

Thanks!

**Comment by thomas-maurice** [comment]
Hey @wzzrd ! I'll will have a look at how it works in galaxy (i.e. just a yaml field) and implement that with git tags, if that looks good to you

**Comment by wzzrd** [comment]
Sounds great!

**Comment by thomas-maurice** [comment]
Just published `v0.0.0`, I will keep incrementing the version every time I merge a bunch of PRs !
