### ISSUE TITLE
Gitea Key not found on Keyserver

### ISSUE THREAD

**Issue by DC7IA** [thomas-maurice/ansible-role-gitea#91]
The key server used to retrieve the key (keyserver.ubuntu.com) for the signature answers to a query for the gitea key with "not found", thus the task "Download gitea asc file" in `install.yml` fails.

The keyserver should be changed to one that has the key. I used keys.gnupg.org, but not sure which server is the most reliable. Maybe the official key server that gitea uses should be used for this role as well.

**Comment by DC7IA** [comment]
That server (keys.gnupg.org) supports `hkps://`, maybe that should be preferred over `hkp://`? :D

**Comment by DO1JLR** [comment]
good idea!
