### ISSUE TITLE
error templating gitea.ini

### ISSUE THREAD

**Issue by stweise** [thomas-maurice/ansible-role-gitea#96]
there are to `endif` blocks in templates/gitea.ini.j2 but just one `if`

if: L 56
endif: L 63
endif: L 69

this leads to templating errors and seems to be in current master as well as v0.0.0
i think deleting the one in L63 should be right.

thanks for all the work you are putting into this, greatly appreciate it
Cheers,
Steffen

**Comment by wzzrd** [comment]
#97 should fix this
